### ISSUE TITLE
Missing package in the freenas build dependencies

### ISSUE THREAD

**Issue by fcannini** [freenas/freenas-build#10]
Hi there

Yesterday (Aug 5th) I tried to follow the instructions to build the freenas 9.10 .iso images in this page:
https://github.com/freenas/freenas-build/wiki/FreeNAS-9.10---10-%E2%80%94-Setting-up-a-FreeNAS-build-environment

The 'make checkout' phase fails with the following error:

`[0:00:01] ==> ERROR: /usr/local/lib/grub/x86_64-efi/zfs.mod not found.  Please run "pkg install sysutils/grub2-efi" or install from ports`

After installing this package, the rest of the process runs fine.

**Comment by jordanhubbard** [comment]
I'm a little puzzled at the docs on the freenas-build wiki.  It lists a manual set of pkgs to install, which are almost certain to be out of date at any given time, vs running the built-in "bootstrap-pkgs" make target which is the one we keep authoritative (and is also obviously much easier to invoke).

**Comment by jordanhubbard** [comment]
Oh, yeah, my suggestion:  Put the git clone of freenas-build earlier in the steps.  Suggest going into freenas-build directory and typing ```make bootstrap-pkgs``` rather than the earlier pkg install steps.

**Comment by kmoore134** [comment]
Done! FYI, it was correct in README.md, but I've updated the wiki page to match now.

**Comment by fcannini** [comment]
Thanks @kmoore134 !

**Comment by justinclift** [comment]
Just noticed this. :wink:

@jordanhubbard If `bootstrap-pkgs` works every time, then yeah, that's approach.  When I wrote that wiki guide though, it was based on trying to simplify this:

&nbsp; &nbsp; https://github.com/freenas/freenas-build/blob/57d173f8af935e0b85e073ca190d2f7fa134d577/README.md

That README.md had this clause in it:

```
You can also use make bootstrap-pkgs to let it install required dependencies
automatically. It will only install whats listed in the Makefile you will need to
install textproc/py-sphinx_numfig from the ports systems as there are no
packages available.
```

Which (at the time) didn't completely work (missing dependencies) for a newly installed VM.  So, it was easier to just have a single "pkg install" line with everything that was actually needed.

But yeah... if the required packages change frequently that's not optimal. :wink:

**Comment by jordanhubbard** [comment]
Yeah, it was the frequently changing nature of the dependencies that made that make target best practice in the first place. Now we have standardized on it.
