### ISSUE TITLE
How do I build FreeNAS 10? Status of FreeNAS 10?

### ISSUE THREAD

**Issue by VoR0220** [freenas/freenas-build#2]
Hey there,

I'm currently very interested in using FreeNAS 10 for a platform. However before I do that, I need to know what the status of the project is. How put together is the middleware? Could I begin development of my own GUI? 

If it's coming along well, how would I go about building and installing this? There's a lot of documentation that seems strewn everywhere and I just want a clear solid answer. If you are behind, what do you need in terms of help? Your interest in getting this done is also my interest in getting this done. 

Thanks in advance

**Comment by jceel** [comment]
Hi,

Middleware is in pretty good shape - it doesn't have feature parity with 9.3 yet, but it's pretty close to. It's definitely good enough to begin development of middleware clients (such as GUIs).

Regarding build, please take a look at: https://github.com/freenas/freenas-build#building-the-system-quickstart-flow. "make checkout" should check out all dependent repositories (such as GUI, middleware and auxiliary libraries) and "make release" should produce installable ISO image.

Once you build and install FreeNAS 10, you can navigate to ```http://<freenas-ip>:8180/apidoc``` to see automatically generated middleware API documentation.

We would greatly appreciate every help with improving code or documentation! (yes, we're aware that docs are far from perfect right now).

**Comment by VoR0220** [comment]
@jceel awesome and thanks for your speedy reply. By any chance are you guys almost integrated with IPFS and Amazon yet?

**Comment by jceel** [comment]
IPFS - yes! It's already in the build. I'm not sure about status of Amazon S3 - will forward that question to person responsible for it ;)

**Comment by VoR0220** [comment]
Cool. Can you forward them here to let me know? Again, thanks for your help. I'll be sure to mark any issues. One more thing though. Any recommendations for somebody trying to install this with OSX?

**Comment by svkamp** [comment]
It depends on how you define "integrated with" as of now we can mount, read, write, backup and restore to amazon serives with various cli tools, such as s3fs, s3-cmd and restic or even become a dedicated S3 capable service on our own, negating the need for amazon itself as we have RIAK CS integrated also. However it requires 3 nodes be deployed, and can expand to X number.

**Comment by VoR0220** [comment]
@svkamp great to know!
