### ISSUE TITLE
profile=freenas9 fails to install - missing packages

### ISSUE THREAD

**Issue by pzi123** [freenas/freenas-build#37]
I performed successful build of freenas9 profile on the FreeBSD 11. The _BE/objs/logs/buildworld completes with:

_### >>> World build completed on Tue Jan 24 01:27:21 MST 2017_

and the .iso is created in:

_./release/FreeNAS-9.10-MASTER-201701240805/x64/FreeNAS-9.10-MASTER-201701240805-9be5cf3fe.iso_

The ssh installation into the testing VM running FreeNAS version=FreeNAS-9.10.1-U3 fails with 'pkg add -f' for two packages:

_root@pzi-fb-1:/usr/home/pzi/freenas-build# make reinstall-package package=freenas host=root@192.168.77.82
[...]
[0:00:05] ==> Failed command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t root@192.168.77.82 pkg add -f /tmp/freenas-migrate93-20170123.txz /tmp/freenas-files-9.10_16270.txz /tmp/freenas-ui-9.10_16270.txz /tmp/freenas-installer-9.10.txz /tmp/freenas-pkgtools-9.10_297.txz /tmp/freenas-docs-9.10_16270.txz
[0:00:05] ==> Returned value: 70
[0:00:05] ==> ERROR: Build failed
*** Error code 1_

Executed the same command locally on the target FreeNAS at .82 and got this error indicating missing packages:

_[root@pzi-fn-2] /tmp# pkg add -f /tmp/freenas-migrate93-20170123.txz /tmp/freenas-files-9.10_16270.txz /tmp/freenas-ui-9.10_16270.txz /tmp/freenas-installer-9.10.txz /tmp/freenas-pkgtools-9.10_297.txz /tmp/freenas-docs-9.10_16270.txz
[...]
Failed to install the following 2 package(s): /tmp/freenas-files-9.10_16270.txz, /tmp/freenas-ui-9.10_16270.txz,
[root@pzi-fn-2] /tmp#_

Drilled deeper one package at the time with pkg add - got more detailed errors pointing to missing dependent packages:

_[root@pzi-fn-2] /tmp# pkg add -f /tmp/freenas-files-9.10_16270.txz
Installing freenas-files-9.10_16270...
package freenas-files is already installed, forced install
pkg: Missing dependency 'py27-snmp_passpersist'_

_[root@pzi-fn-2] /tmp# pkg add -f /tmp/freenas-ui-9.10_16270.txz
Installing freenas-ui-9.10_16270...
package freenas-ui is already installed, forced install
pkg: Missing dependency 'py27-django-formtools'_

Next located the missing packages in the build tree and copied them by hand to /tmp in the target and installed them by hand.  Retried the installation of the 2 failed packages and got more missing dependencies:

_[root@pzi-fn-2] /tmp# pkg add -f /tmp/freenas-files-9.10_16270.txz
Installing freenas-files-9.10_16270...
package freenas-files is already installed, forced install
Extracting freenas-files-9.10_16270:  29%
pkg: archive_read_extract() errno 2: Can't create '/compat/linux/proc/.donotremove'
Extracting freenas-files-9.10_16270: 100%
Deleting files for freenas-files-9.10_16270: 100%_

Failed to install the following 1 package(s): /tmp/freenas-files-9.10_16270.txz

_[root@pzi-fn-2] /tmp# pkg add -f /tmp/freenas-ui-9.10_16270.txz
Installing freenas-ui-9.10_16270...
package freenas-ui is already installed, forced install
pkg: Missing dependency 'py27-middlewared'_

Failed to install the following 1 package(s): /tmp/freenas-ui-9.10_16270.txz_

Any pointers on what went wrong and how to move forward?
thanks
-Peter

**Comment by pzi123** [comment]
It looks like this package dependency issue is limited to the make reinstall-package target. Since the test FreeNAS that I was using to upgrade using make/ssh was not bootable anymore I took generated ISO and reinstalled it and all went ok - no missing packages. That ISO is complete. Verified one of the missing packages and it was installed:

_[root@pzi-fn-2] ~# pkg info | grep py27-middlewared
py27-middlewared-9.10_16270    FreeNAS Middleware Daemon_

That reinstall-package method would be really useful if it worked.  I hope we can find the resolution.

**Comment by justinclift** [comment]
Ahhh interesting.  I tried to update an already installed FreeNAS 9.10 box last week (first time trying this) and the process broke + made the box unbootable.  Since it was only a test system though, I didn't bother to capture the error output, but (from memory) it was similar to the ones you're showing.

**Comment by pzi123** [comment]
I think that this instructions to update running FreeNAS provided at https://github.com/freenas/freenas-build/blob/master/README.md

_make update
make ports
make reinstall-package package=freenas host=root@1.2.3.4_

should be taken with the grain of salt. They assume that freenas package does not have dependencies on other packages introduced since your target was installed.

There is also one more make target side by side with 'reinstall-packge' - 'reinstall-latest' and this one is certainly a killer.  It takes all generated packages (about 393 .txz), scp them to /tmp and runs the -f install (pkg add):

_reinstall-latest:
        @${BUILD_TOOLS}/reinstall-package.py install_latest ${host}_

That procedure simply takes the running freenas offline - the console is not responsive. No wonder - it just wrote over every configuration file freebsd has.

**Comment by jordanhubbard** [comment]
This is why we don't document `reinstall-latest` in the README.  It's not meant to be used casually during development. :)

**Comment by pzi123** [comment]
so what is the proper update procedure after the successful source build? We have the iso but we don't want to reinstall. In other words how do we replicate the procedure the GUI system->update performs but based on the local build?

**Comment by jordanhubbard** [comment]
You grab the .tar file left in the release/ directory by the build and you give it as an argument to the freenas-update command.

**Comment by justinclift** [comment]
Cool, lets get the doc updated with that. :smile:

**Comment by pzi123** [comment]
thanks Jordan - it worked:

_pzi@pzi-fb-1:/usr/home/pzi/freenas-build/freenas9/_BE/release$ scp FreeNAS-9.10-MASTER-201701240805-unsigned.tar root@pzi-fn-3:/tmp
[root@pzi-fn-3] /tmp# freenas-update FreeNAS-9.10-MASTER-201701240805-unsigned.tar_
